version: "3.8"

services:
  postgres:
    image: postgres
    container_name: task-manager-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgres-data:
